version: "3"
volumes:
  vol:
services:
  node:
    build: .
    networks:
      - db
    volumes:
      - vol:/src/logs
    ports:
      - "${PORT}:${PORT}"
    restart: always

networks:
  db:
    external:
      name: my-bridge

